defaultProject: shikanime-studio-labs
defaultLocation: europe-west9
defaultDataset: seeker
defaultAssertionDataset: seeker_assertions
vars:
  sgDatalakeBucketUri: gs://shikanime-studio-labs-seeker-europe-west9-sg-datalake
